aposin/LicenseScout

LICENSE

[DGS] Fix License formatting

---

README.md

Add README badges to quickly summarize status/project properties.

[DGS] Add README badges

---

.github/ISSUE_TEMPLATE/bug_report.md

[MH] updated issue template with default labels

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

This PR includes the following changes (one commit per change):
- Fix bug template: the 'label' metadata is not correct, but 'labels'  should be used (note that I have overseen this in #7). Also, it sets all the rest of available metadata as empty to avoid this happening in the future if someone wants to add extra information.
- Add metadata to feature template: to keep in sync with the bug template.
- Propose a new priority ("Prio") label to mark issues as not prioritized ("Triage" priority). This can help maintainers to identify those issues and assign priority as soon as possible.

[DGS] Issue template fixes and new values

---

.travis.yml
README.md

This changes adds the travis pipeline to run the compilation and the tests/checks.
Also adds the badge on the README.

[DGS] Add travis build

---

.travis.yml
org.aposin.licensescout.core/LICENSE_header.txt
org.aposin.licensescout.core/pom.xml

Looks like travis couldn't parse the YML.
They don't provide anymore a linting tool for its own config file, so I just tested the file to be in yaml compliant (using http://www.yamllint.com/)

Fix travis.yml

---

org.aposin.licensescout.core/pom.xml
org.aposin.licensescout.core/src/it/java-html/verify.groovy
org.aposin.licensescout.core/src/it/simple-it/verify.groovy
org.aposin.licensescout.core/src/main/resources/templates/license_report.vm

Add license header to non-java sources.

[DGS] Include license header in other sources

---

.travis.yml
NOTICE.txt
README.md
org.aposin.licensescout.core/pom.xml
org.aposin.licensescout.parent/pom.xml

This PR adds the following features for document the code coverage of the project:
* Add Maven Plug-in for JaCoCo and attach to the test phase (**first commit**). This allows to generate the JaCoCo report locally or in the build (which will be used by Codecov, see below).
* Add Codecov service to be included in the process (**second commit**). This parses the JaCoCo report and provides an online summary with coverage statistics. The information could be reach by the badge added to the README file.

Add jacoco/codecov reports 

---

README.md

Add badge with known vulnerabilties from https://snyk.io/

[DGS] Add vulnerabilities badge (snyk.io)

---

.github/PULL_REQUEST_TEMPLATE.md
CODING_MANIFEST.md

Typo fixes in the general docs.
Matthias Holzer / Allianz Technology GmbH

Mh fixed typos

---

.travis.yml

Workaround to avoid failing builds on Travis due to artifact download problems.
#20 
Add travis cache directories, concretely the .m2 folder
Slower travis build and possible build errors (see #20) due to maven repository not cached.
More stable/faster build on travis.

[DGS] Add .m2 to travis cached directories

---

org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/main/Main.java
org.aposin.licensescout.core/src/test/java/org/aposin/licensescout/main/MainTest.java

Signed-off-by: Matthias Holzer <matthias.holzer@allianz.at>
did some changes in the main method. 
refactored basic functionality 
Matthias Holzer, Allianz Technology GmbH

[MH] refactored main class

---

.gitattributes

Added .gitattributes file to prevent automatic end-of-files conversion on checkout.
https://github.com/aposin/LicenseScout/issues/26
It prevents that all imported projects files are marked as changes in IDEs right after the checkout because of the automatic conversion of the end-of-file characters.
Disabled the automatic EOF conversion on repository.
Bug is fixed.
Bug is fixed.
one configuration file added.
A fork was created.
The .gitattributes file was added there.
The fork was newly cloned and imported in Eclipse IDE.
The just imported projects do not show any difference when synchronized to the remote.

Fix for #26

---

org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/finder/JavascriptNpmFinder.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/license/LicenseCheckedList.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/mojo/AbstractScanMojo.java

Fixing some of the code quality issues as mentioned in Codacy : 
- [Avoid unused method parameters](https://app.codacy.com/manual/aposin-bot/LicenseScout/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiQ2F0ZWdvcnkiLCJ2YWx1ZXMiOltudWxsXX0seyJpZCI6IkxldmVsIiwidmFsdWVzIjpbbnVsbF19LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbNTUzMV19LHsiaWQiOiJBdXRob3IiLCJ2YWx1ZXMiOltudWxsXX1d)
- [Avoid unused private methods](https://app.codacy.com/manual/aposin-bot/LicenseScout/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiQ2F0ZWdvcnkiLCJ2YWx1ZXMiOltudWxsXX0seyJpZCI6IkxldmVsIiwidmFsdWVzIjpbbnVsbF19LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbNTM3OV19LHsiaWQiOiJBdXRob3IiLCJ2YWx1ZXMiOltudWxsXX1d)
https://github.com/aposin/LicenseScout/issues/35 …

gh #35 : Fix code quality - Avoid unused parameters and method

---

org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/finder/JavaJarFinder.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/license/LicenseCheckedList.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/license/LicenseStoreData.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/model/Notices.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/model/Providers.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/util/sax/AbstractSaxHandler.java

Code cleaning for better readability and codacy issues reduction.
https://github.com/aposin/LicenseScout/issues/35
Code was cleaned up to reduce the number of codacy issues.
Code was cleaned up to reduce the number of codacy issues.
Some code was generating codacy issues.
Code was cleaned up to reduce the codacy issues.
30 min.
D. Ceraso
Project was build in Eclipse and tests were run.

(#35) fix codacy issues

---

org.aposin.licensescout.core/src/test/java/org/aposin/licensescout/util/JsonUtilTest.java
org.aposin.licensescout.core/src/test/resources/package-multiple-licenses.json
org.aposin.licensescout.core/src/test/resources/package-no-license.json
org.aposin.licensescout.core/src/test/resources/package.json

Increase Unit Test Coverage
Added Unit Tests for JsonUtil #34 
Sreekanth Nelakurthi
Unit Test with coverage

Unit Tests for JsonUtil

---

org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/finder/JavaJarFinder.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/license/LicenseCheckedList.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/license/LicenseStoreData.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/model/Notices.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/model/Providers.java

Fixing some of the code quality issues as mentioned in [Codacy - LicenseScout](https://app.codacy.com/manual/aposin-bot/LicenseScout/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6WyJKYXZhIl19LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJFcnJvclByb25lIl19LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiUGF0dGVybiIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiQXV0aG9yIiwidmFsdWVzIjpbbnVsbF19XQ==)
https://github.com/aposin/LicenseScout/issues/35
Fixing code quality issues as reported in **Codacy**. 
- Link of issues fixed : [url](https://app.codacy.com/manual/aposin-bot/LicenseScout/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6WyJKYXZhIl19LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJFcnJvclByb25lIl19LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiUGF0dGVybiIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiQXV0aG9y …

gh #35 : Fix code quality

---

README.md

full documentation is located in org.aposin.licensescout.documentation
Signed-off-by: Robert Mlekus <Robert.Mlekus@gmail.com>
#53 
1 line of code (markdown documentation)
Robert Mlekus

Update README.md to fix "full documentation" link

---

org.aposin.licensescout.core/src/test/java/org/aposin/licensescout/finder/JavaJarFinderTest.java
org.aposin.licensescout.core/src/test/java/org/aposin/licensescout/mojo/AbstractScanMojoTest.java
org.aposin.licensescout.core/src/test/java/org/aposin/licensescout/mojo/JavaScanMojoTest.java
org.aposin.licensescout.core/src/test/java/org/aposin/licensescout/mojo/NpmScanMojoTest.java

Test cases for ScanMojo classes
New unit tests.
Added test cases
Executing the new tests.

Scanmojo tests

---

org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/database/DatabaseWriter.java

Changed database code to use prepared statements
Solved #71 
Using PreparedStatements instead of unsafe string concatenation
Running Licensescout writing to a local test database

Changed database code to use prepared statements

---

org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/archive/Archive.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/archive/ArchiveIdentifierMessageDigest.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/finder/JavaJarFinder.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/license/LicenseCheckedList.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/model/LSMessageDigest.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/util/CryptUtil.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/util/MiscUtil.java
org.aposin.licensescout.core/src/test/java/org/aposin/licensescout/license/LicenseUtilEvaluateLicensesTest.java
org.aposin.licensescout.core/src/test/java/org/aposin/licensescout/model/LSMessageDigestTest.java
org.aposin.licensescout.core/src/test/java/org/aposin/licensescout/util/CryptUtilTest.java
org.aposin.licensescout.core/src/test/java/org/aposin/licensescout/util/MiscUtilTest.java

New class LSMessageDigest to hold byte array of a message digest
- additional unit tests
change byte array that holds a message digest to using a class.
Executing all uni tests.

Message digest refactoring

---

org.aposin.licensescout.core/pom.xml
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/database/DatabaseWriter.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/execution/ExecutionParameters.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/execution/Executor.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/finder/FinderFactory.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/finder/JavascriptNpmFinder.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/finder/LicenseScoutExecutionException.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/license/ArtifactServerUtil.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/mojo/AbstractScanMojo.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/mojo/JavaScanMojo.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/mojo/NpmScanMojo.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/util/MiscUtil.java
org.aposin.licensescout.core/src/test/java/org/aposin/licensescout/core/test/util/CreateJarFileHelper.java
org.aposin.licensescout.core/src/test/java/org/aposin/licensescout/core/test/util/TestUtil.java
org.aposin.licensescout.core/src/test/java/org/aposin/licensescout/execution/SimpleExecutionTest.java
org.aposin.licensescout.core/src/test/java/org/aposin/licensescout/exporter/AbstractExporterTest.java
org.aposin.licensescout.core/src/test/java/org/aposin/licensescout/exporter/CsvExporterTest.java
org.aposin.licensescout.core/src/test/java/org/aposin/licensescout/finder/BaseFinderTest.java
org.aposin.licensescout.core/src/test/java/org/aposin/licensescout/finder/FinderFactoryTest.java
org.aposin.licensescout.core/src/test/java/org/aposin/licensescout/finder/JavaJarFinderTest.java
org.aposin.licensescout.core/src/test/java/org/aposin/licensescout/mojo/AbstractScanMojoTest.java
org.aposin.licensescout.core/src/test/java/org/aposin/licensescout/mojo/JavaScanMojoTest.java
org.aposin.licensescout.core/src/test/java/org/aposin/licensescout/mojo/NpmScanMojoTest.java
org.aposin.licensescout.core/src/test/java/org/aposin/licensescout/util/MiscUtilTest.java
org.aposin.licensescout.parent/pom.xml

Refactoring of the main control flow of the LicenseScout
The main control flow of the LicenseScout was in the mathod AbstractScanMojo.execute(). During a Maven execution, the subclasses of AbstractScanMojo are instantiated by the Maven runtime system and get their private and protected members set from Maven parameters. However, this behaviour is very complicated to emulate in a unit test case, making it nearly impossible to write unit tests for the main control flow.
The refactoring separates the control flow into a class that is a POJO independent of Maven classes. This way, it is possible to write unit tests for the execution.
In the future, this separation will also allow to write a different "frontend" to the LicenseScout execution engine, for instance a Gradle plugin.
Main content …

Xxecution refactoring

---

org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/finder/AbstractFinder.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/finder/JavaJarFinder.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/finder/JavascriptNpmFinder.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/util/CryptUtil.java
org.aposin.licensescout.core/src/test/java/org/aposin/licensescout/util/CryptUtilTest.java

Finder and CrytUtil refactoring
None
Refactoring of Finder classes and CryptUtil
Especially JavaJarFinder is way to complex to be maintainable. This is a first step of simplification and consolidation.
Refactoring.

Finder and CrytUtil refactoring

---

org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/finder/AbstractFinder.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/finder/JavaJarFinder.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/finder/JavascriptNpmFinder.java
org.aposin.licensescout.core/src/test/java/org/aposin/licensescout/finder/JavaJarFinderTest.java

More finder refactorings
fixed bug #68 
#68 

More finder refactorings; fixed bug

---

licensescout-maven-plugin/.gitignore
licensescout-maven-plugin/src/site/asciidoc/download.adoc
licensescout-maven-plugin/src/site/asciidoc/examples/alternative-attach.adoc
licensescout-maven-plugin/src/site/asciidoc/examples/alternative-dbms.adoc
licensescout-maven-plugin/src/site/asciidoc/examples/buildurl-jenkins.adoc
licensescout-maven-plugin/src/site/asciidoc/examples/controlling-execution.adoc
licensescout-maven-plugin/src/site/asciidoc/examples/custom-output-filenames.adoc
licensescout-maven-plugin/src/site/asciidoc/examples/custom-templates.adoc
licensescout-maven-plugin/src/site/asciidoc/examples/filesystem-config-files.adoc
licensescout-maven-plugin/src/site/asciidoc/examples/output-encoding.adoc
licensescout-maven-plugin/src/site/asciidoc/examples/scan-maven-dependencies.adoc
licensescout-maven-plugin/src/site/asciidoc/usage.adoc
licensescout-maven-plugin/src/site/site.xml

Site documentation for future plugin project 'licensescout-maven-plugin'
Note: the base directory ('maven-licensesccout-plugin') reflects the future split of the maven plugin part from the core and the naming convention that the name of the base directory should be the same as the artifactId (there are several tools that assume this naming convention and result in funny effects or simply do not work if the naming convention is not followed.

Site documentation for future plugin project 'licensescout-maven-plugin'

---

org.aposin.licensescout.core/src/it/help-general/invoker.properties
org.aposin.licensescout.core/src/it/java-csv-artifact-configuration/pom.xml
org.aposin.licensescout.core/src/it/java-csv-artifact-configuration/verify.groovy
org.aposin.licensescout.core/src/it/java-csv-file-configuration/invoker.properties
org.aposin.licensescout.core/src/it/java-csv-file-configuration/pom.xml
org.aposin.licensescout.core/src/it/java-csv-file-configuration/verify.groovy
org.aposin.licensescout.core/src/it/java-html-artifact-configuration/pom.xml
org.aposin.licensescout.core/src/it/java-html-artifact-configuration/verify.groovy
org.aposin.licensescout.core/src/it/java-txt-artifact-configuration/pom.xml
org.aposin.licensescout.core/src/it/java-txt-artifact-configuration/verify.groovy
org.aposin.licensescout.core/src/it/npm-txt-artifact-configuration/pom.xml
org.aposin.licensescout.core/src/it/npm-txt-artifact-configuration/verify.groovy
org.aposin.licensescout.core/src/it/npm-txt-file-configuration/pom.xml
org.aposin.licensescout.core/src/it/npm-txt-file-configuration/verify.groovy

Integration Test rework
Fixed problems with integration tests. Added integration tests for new configuration features.

Integration Test rework

---

.codacy.yml

Checks for ANSI SQL make no sense in case of the .sql files used in LicenseScout to create tables because the files are specific for different DBMS.
This issue blocks the integration of #77 

Excluding SQL files from Codacy checks

---

licensescout-maven-plugin/src/site/asciidoc/download.adoc
licensescout-maven-plugin/src/site/asciidoc/examples/alternative-attach.adoc
licensescout-maven-plugin/src/site/asciidoc/examples/alternative-dbms.adoc
licensescout-maven-plugin/src/site/asciidoc/examples/custom-templates.adoc
licensescout-maven-plugin/src/site/asciidoc/examples/output-encoding.adoc
licensescout-maven-plugin/src/site/asciidoc/usage.adoc
licensescout-maven-plugin/src/site/site.xml
licensescout-maven-utils/pom.xml
licensescout-maven-utils/src/main/java/org/aposin/licensescout/maven/utils/ArtifactItem.java
licensescout-maven-utils/src/site/asciidoc/download.adoc
licensescout-maven-utils/src/site/asciidoc/usage.adoc
licensescout-maven-utils/src/site/site.xml
licensescout-report-maven-plugin/pom.xml
licensescout-report-maven-plugin/src/main/java/org/aposin/licensescout/report/exporter/DoxiaExporter.java
licensescout-report-maven-plugin/src/main/java/org/aposin/licensescout/report/exporter/DoxiaReportExporterFactory.java
licensescout-report-maven-plugin/src/site/asciidoc/download.adoc
licensescout-report-maven-plugin/src/site/asciidoc/usage.adoc
licensescout-report-maven-plugin/src/site/site.xml
org.aposin.licensescout.core/pom.xml
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/execution/StandardReportExporterFactory.java
org.aposin.licensescout.core/src/main/java/org/aposin/licensescout/finder/JavaJarFinder.java
org.aposin.licensescout.core/src/site/asciidoc/download.adoc
org.aposin.licensescout.core/src/site/asciidoc/usage.adoc
org.aposin.licensescout.core/src/site/site.xml
org.aposin.licensescout.core/src/test/java/org/aposin/licensescout/exporter/HtmlExporterTest.java
org.aposin.licensescout.documentation/pom.xml
org.aposin.licensescout.documentation/src/site/asciidoc/maintenance/maintenance.adoc
org.aposin.licensescout.documentation/src/site/asciidoc/usermanual/configuration.adoc
org.aposin.licensescout.parent/pom.xml

- Documentation updates
- added configuration for site generation
- POM cleanup
- added parameter check in
Making maven site generation work

Site generation and documentation Part 2

---

licensescout-core/src/main/java/org/aposin/licensescout/execution/BaseLicenseScoutExecutionException.java
licensescout-core/src/main/java/org/aposin/licensescout/execution/ExecutionParameters.java
licensescout-core/src/main/java/org/aposin/licensescout/execution/Executor.java
licensescout-core/src/main/java/org/aposin/licensescout/execution/LicenseScoutFailOnErrorException.java
licensescout-core/src/main/java/org/aposin/licensescout/model/AlarmCause.java
licensescout-core/src/test/java/org/aposin/licensescout/execution/SimpleExecutionTest.java
licensescout-core/src/test/java/org/aposin/licensescout/util/AbstractLogTest.java
licensescout-core/src/test/java/org/aposin/licensescout/util/JavaUtilLogTest.java
licensescout-maven-plugin/src/main/java/org/aposin/licensescout/mojo/AbstractScanMojo.java
licensescout-maven-utils/pom.xml
licensescout-maven-utils/src/test/java/org/aposin/licensescout/maven/utils/MavenLogTest.java
licensescout-report-maven-plugin/src/main/java/org/aposin/licensescout/report/mojo/AbstractReportMojo.java

First implementation of fail-on-error if artifacts are detected with a certain LigalStatus (reflecting that they have no license detected or the license is not accepted.
This is a first version that is suficient to let the LicenseScout run on itself as a chck for unaccepted licenses.
However, in the future it is desirable to have a more complete concept of failue levels and reasons so that also conditions in reading configuration files (as requested by #58 ) are part of a consistent system.
New test cases in SimpleExecutionTest

Fail-on-error for licenses

---

licensescout-maven-plugin/src/main/java/org/aposin/licensescout/mojo/AbstractScanMojo.java

Throwing MojoFailureException instead of MojoExecutionException gives a more clear message on build failures due to fail-on-error.

Fixed MOJO failure exception

---

licensescout-documentation/src/site/asciidoc/maintenance/maintenance.adoc
licensescout-parent/pom.xml

#22 
Doing a release and verify the tag in the repository.

Added tagging in release profile

---

licensescout-core/src/main/java/org/aposin/licensescout/finder/JarEntryContainer.java
licensescout-core/src/main/java/org/aposin/licensescout/finder/JarFinderHandler.java

Fixed exception in case of zero length file

---

licensescout-core/src/main/java/org/aposin/licensescout/configuration/ConfigFileHandler.java
licensescout-core/src/main/java/org/aposin/licensescout/execution/ExecutionParameters.java
licensescout-core/src/main/java/org/aposin/licensescout/execution/Executor.java
licensescout-core/src/main/java/org/aposin/licensescout/license/LicenseCheckedList.java
licensescout-core/src/main/java/org/aposin/licensescout/license/LicenseStoreData.java
licensescout-core/src/main/java/org/aposin/licensescout/model/Notices.java
licensescout-core/src/main/java/org/aposin/licensescout/model/Providers.java
licensescout-core/src/main/java/org/aposin/licensescout/util/CryptUtil.java
licensescout-core/src/main/java/org/aposin/licensescout/util/MiscUtil.java
licensescout-core/src/test/java/org/aposin/licensescout/core/test/util/CreateJarFileHelper.java
licensescout-core/src/test/java/org/aposin/licensescout/finder/BaseFinderTest.java
licensescout-core/src/test/java/org/aposin/licensescout/util/CryptUtilTest.java
licensescout-maven-plugin/src/main/java/org/aposin/licensescout/mojo/AbstractScanMojo.java
licensescout-report-maven-plugin/src/main/java/org/aposin/licensescout/report/mojo/AbstractReportMojo.java

Also:
- using utility class XmlStreamReader to parse XML config files in the
correct encoding
#84 
See #84 
Executing all unit and integration tests.

Made message digest algorithm configurable

---

licensescout-core/src/main/java/org/aposin/licensescout/finder/JavaJarFinder.java

If a scanned directory contains a directory META-INF, the LicenseScout considered it an unpacked archive directory. Subsequently, LicenseScout tries to read the file META-INF/MANIFEST.MF.  Now if this file does not exist archive meta data are not available, which leads to an exception.
Solved by refining the logic of detecting an unpacked archive directory: the existance of the file META-INF/MANIFEST.MF is checked early.
Running all unit and integration tests.

Fix for exception when directory contains META-INF, but not MANIFEST.MF

---

licensescout-core/src/main/java/org/aposin/licensescout/execution/ExecutionParameters.java
licensescout-core/src/main/java/org/aposin/licensescout/execution/Executor.java
licensescout-core/src/main/java/org/aposin/licensescout/execution/ScanLocation.java
licensescout-core/src/main/java/org/aposin/licensescout/finder/FinderFactory.java
licensescout-core/src/test/java/org/aposin/licensescout/execution/ScanLocationTest.java
licensescout-core/src/test/java/org/aposin/licensescout/execution/SimpleExecutionTest.java
licensescout-core/src/test/java/org/aposin/licensescout/finder/FinderFactoryTest.java
licensescout-maven-plugin/src/main/java/org/aposin/licensescout/mojo/AbstractScanMojo.java
licensescout-report-maven-plugin/src/main/java/org/aposin/licensescout/report/mojo/AbstractReportMojo.java

Executing all unit and integration tests

Replaced parameters scanDirectory by Objects of type ScanLocation

---

licensescout-maven-plugin/src/main/java/org/aposin/licensescout/mojo/AbstractScanMojo.java
licensescout-maven-utils/src/main/java/org/aposin/licensescout/maven/utils/ArtifactHelper.java
licensescout-maven-utils/src/main/java/org/aposin/licensescout/maven/utils/ArtifactScope.java
licensescout-maven-utils/src/main/java/org/aposin/licensescout/maven/utils/LSArtifact.java
licensescout-maven-utils/src/test/java/org/aposin/licensescout/maven/utils/ArtifactHelperTest.java
licensescout-maven-utils/src/test/java/org/aposin/licensescout/maven/utils/ArtifactServerUtilHelperTest.java
licensescout-maven-utils/src/test/java/org/aposin/licensescout/maven/utils/ConfigurationHelperTest.java
licensescout-maven-utils/src/test/java/org/aposin/licensescout/maven/utils/NexusArtifactUrlBuilderTest.java
licensescout-report-maven-plugin/src/main/java/org/aposin/licensescout/report/mojo/AbstractReportMojo.java

- addded utility methods for dependency resolution
-added configuration parameters to maven plugins to allow configuring a set of artifacts as starting point instead of a scan directory
- extended unit tests
- refactorings
Executing all unit and integration tests, including the new ones for the new utility method.

Utility methods for Maven scan mode

---

README.md

Updated Maven central badge

---

licensescout-core/pom.xml
licensescout-core/src/main/java/org/aposin/licensescout/license/LicenseStoreData.java
licensescout-parent/pom.xml

Reworked reading CSV for name and URL mapping on the basis of Apache commons-csv

Reworked reading CSV for name and URL mapping

---

licensescout-core/pom.xml
licensescout-documentation/src/site/asciidoc/usermanual/database.adoc
licensescout-maven-plugin/src/site/asciidoc/examples/alternative-dbms.adoc
licensescout-parent/pom.xml

- removed hard coded dependency to mariadb JDBC driver
- adapted documentation
The hard coded dependency to the mariaDB JDBC driver caused rouble in some build - the driver was not loaded correctly.
So the solution was to remove this dependency, reuiring to configure the locally used JDBC driver where the LicenseScout is used by injecting a dependency in the Maven plugin configuration (see documentation).

JDBC driver rework

---

licensescout-core/src/main/java/org/aposin/licensescout/finder/AbstractJavaFinder.java
licensescout-core/src/main/java/org/aposin/licensescout/finder/FilesystemFinderHandler.java
licensescout-core/src/main/java/org/aposin/licensescout/finder/FinderHandler.java
licensescout-core/src/main/java/org/aposin/licensescout/finder/JarFinderHandler.java
licensescout-core/src/main/java/org/aposin/licensescout/finder/JavaJarFinder.java

Improved warning "file has length of zero bytes" by adding the file path to the message

Improve logging message

---

licensescout-core/src/main/java/org/aposin/licensescout/configuration/ConfigFileHandler.java
licensescout-core/src/main/java/org/aposin/licensescout/configuration/FilesystemConfigFileHandler.java
licensescout-core/src/main/java/org/aposin/licensescout/configuration/ZipConfigFileHandler.java
licensescout-core/src/main/java/org/aposin/licensescout/execution/Executor.java
licensescout-core/src/test/java/org/aposin/licensescout/configuration/AbstractConfigFileHandlerTest.java
licensescout-core/src/test/java/org/aposin/licensescout/configuration/FileSystemConfigFileHandlerTest.java
licensescout-core/src/test/java/org/aposin/licensescout/configuration/ZipConfigFileHandlerTest.java
licensescout-core/src/test/resources/configuration_sample_test/license_report_txt_custom.vm

So far, license report templates packagd into a configuration bundle were not loaded correctly (only loading from file system was working). This PR fixes this by moving the loading of templates to ConfigFileHandler.

Fix loading license report templates from config bundle

---

licensescout-core/src/main/resources/templates/license_report_html_default.vm

Moved provider column in default HTML report to a more convenient position.

Moved provider column in default HTML report
